# Generated by Django 3.2.25 on 2024-06-06 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('corpo', models.TextField(max_length=1000)),
                ('modelo', models.CharField(choices=[('Vitoria', 'Vitória'), ('Ricardo', 'Ricardo'), ('Camila', 'Camila')], default='Camila', max_length=50, verbose_name='Modelo de voz')),
                ('formato', models.CharField(choices=[('mp3', 'mp3'), ('ogg', 'ogg')], default='mp3', max_length=4)),
                ('datacriado', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação')),
                ('NomeInterno', models.CharField(default='xU9OXB42p6uwq4OMwHGf', max_length=20, verbose_name='Nome Interno')),
                ('CaminhoInterno', models.CharField(default='/media/Included/temp/', max_length=50, verbose_name='Caminho Interno')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arquivos de Voz',
                'verbose_name_plural': 'Arquivos de Voz',
            },
        ),
    ]
