# Generated by Django 3.2.25 on 2024-05-13 21:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('corpo', models.CharField(max_length=1000)),
                ('modelo', models.CharField(max_length=50)),
                ('formato', models.CharField(max_length=3)),
                ('datacriado', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
