# Generated by Django 3.2.25 on 2024-06-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakermain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakfile',
            name='NomeInterno',
            field=models.CharField(default='LG1438qzfs6OOaTVcndf', max_length=20, verbose_name='Nome Interno'),
        ),
    ]
