# Generated by Django 4.2.16 on 2024-11-12 17:33

from django.db import migrations, models
import speakermain.models


class Migration(migrations.Migration):

    dependencies = [
        ('speakermain', '0003_auto_20240606_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakfile',
            name='NomeInterno',
            field=models.CharField(default=speakermain.models.gerarNomeInterno, max_length=20, verbose_name='Nome Interno'),
        ),
    ]
