# Generated by Django 3.2.25 on 2024-05-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakermain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakfile',
            name='corpo',
            field=models.TextField(max_length=1000),
        ),
    ]
