# Generated by Django 3.2.25 on 2024-05-27 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('speakermain', '0004_speakfile_identificador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speakfile',
            name='identificador',
        ),
        migrations.AddField(
            model_name='speakfile',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
