# Generated by Django 3.2.25 on 2024-05-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakermain', '0005_auto_20240527_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakfile',
            name='CaminhoInterno',
            field=models.CharField(default='.\\speakermain\\Included\\Speakfiles\temp', max_length=200, verbose_name='Caminho Interno'),
        ),
        migrations.AddField(
            model_name='speakfile',
            name='NomeInterno',
            field=models.CharField(max_length=20, null=True, verbose_name='Nome Interno'),
        ),
    ]
