# Generated by Django 3.2.25 on 2024-06-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakermain', '0006_auto_20240527_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakfile',
            name='CaminhoInterno',
            field=models.CharField(default='/media/Included/temp/', max_length=50, verbose_name='Caminho Interno'),
        ),
        migrations.AlterField(
            model_name='speakfile',
            name='NomeInterno',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nome Interno'),
        ),
    ]
