# Generated by Django 3.2.25 on 2024-06-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakermain', '0007_auto_20240602_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakfile',
            name='NomeInterno',
            field=models.CharField(default='Kh5kM98IhAaYRklv0bGG', max_length=20, verbose_name='Nome Interno'),
        ),
    ]
