# Generated by Django 3.2.25 on 2024-06-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakermain', '0011_alter_speakfile_nomeinterno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakfile',
            name='NomeInterno',
            field=models.CharField(default='DUGlEyFhsWmJnpmutzKd', max_length=20, verbose_name='Nome Interno'),
        ),
        migrations.AlterField(
            model_name='speakfile',
            name='formato',
            field=models.CharField(choices=[('mp3', 'mp3'), ('ogg', 'ogg')], default='mp3', max_length=4),
        ),
        migrations.AlterField(
            model_name='speakfile',
            name='modelo',
            field=models.CharField(choices=[('Vitória', 'Vitória'), ('Ricardo', 'Ricardo'), ('Camila', 'Camila')], default='Camila', max_length=50, verbose_name='Modelo de voz'),
        ),
    ]
