# Generated by Django 3.2.25 on 2024-06-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakermain', '0012_auto_20240605_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakfile',
            name='NomeInterno',
            field=models.CharField(default='BFLR4tvwXEuwZ6QgkAao', max_length=20, verbose_name='Nome Interno'),
        ),
        migrations.AlterField(
            model_name='speakfile',
            name='modelo',
            field=models.CharField(choices=[('Vitoria', 'Vitória'), ('Ricardo', 'Ricardo'), ('Camila', 'Camila')], default='Camila', max_length=50, verbose_name='Modelo de voz'),
        ),
    ]
