# Generated by Django 3.2.25 on 2024-06-06 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import speakermain.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('speakermain', '0013_auto_20240605_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakfile',
            name='NomeInterno',
            field=models.CharField(default='sXsoeAw2dEZ8JB0k0m2F', max_length=20, verbose_name='Nome Interno'),
        ),
        migrations.AlterField(
            model_name='speakfile',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
