# Generated by Django 3.2.25 on 2024-06-06 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakermain', '0014_auto_20240605_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakfile',
            name='NomeInterno',
            field=models.CharField(default='eL02BbRcCOziK9nUaq66', max_length=20, verbose_name='Nome Interno'),
        ),
    ]
