# Generated by Django 3.2.25 on 2024-06-06 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('speakermain', '0015_alter_speakfile_nomeinterno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakfile',
            name='NomeInterno',
            field=models.CharField(default='AM3KLQI4xbY9eiwHKrz9', max_length=20, verbose_name='Nome Interno'),
        ),
        migrations.AlterField(
            model_name='speakfile',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
