# Generated by Django 3.2.25 on 2024-06-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakermain', '0016_auto_20240605_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakfile',
            name='NomeInterno',
            field=models.CharField(default='hME1bZkfAD7gtQIxHokI', max_length=20, verbose_name='Nome Interno'),
        ),
    ]
