# Generated by Django 3.2.25 on 2024-06-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakermain', '0018_alter_speakfile_nomeinterno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakfile',
            name='NomeInterno',
            field=models.CharField(default='rBMGFXuIQ9ytOkPj0ogw', max_length=20, verbose_name='Nome Interno'),
        ),
    ]
