# Generated by Django 3.2.25 on 2024-06-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakermain', '0019_alter_speakfile_nomeinterno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakfile',
            name='NomeInterno',
            field=models.CharField(default='y4DUzYqjZdDH3AWWQIpI', max_length=20, verbose_name='Nome Interno'),
        ),
    ]
